package com.ai.bdex.dataexchange.aipcenter.dao.model;

import java.util.Date;

public class AipScopeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aip_scope_info.SCOPE_ID
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    private String scopeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aip_scope_info.STATUS
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aip_scope_info.CREATE_TIME
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aip_scope_info.CREATE_STAFF
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    private String createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aip_scope_info.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aip_scope_info.UPDATE_STAFF
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    private String updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aip_scope_info.TYPE
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aip_scope_info.SERVICE_ID
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    private String serviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aip_scope_info.SCOPE_ID
     *
     * @return the value of t_aip_scope_info.SCOPE_ID
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public String getScopeId() {
        return scopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aip_scope_info.SCOPE_ID
     *
     * @param scopeId the value for t_aip_scope_info.SCOPE_ID
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public void setScopeId(String scopeId) {
        this.scopeId = scopeId == null ? null : scopeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aip_scope_info.STATUS
     *
     * @return the value of t_aip_scope_info.STATUS
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aip_scope_info.STATUS
     *
     * @param status the value for t_aip_scope_info.STATUS
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aip_scope_info.CREATE_TIME
     *
     * @return the value of t_aip_scope_info.CREATE_TIME
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aip_scope_info.CREATE_TIME
     *
     * @param createTime the value for t_aip_scope_info.CREATE_TIME
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aip_scope_info.CREATE_STAFF
     *
     * @return the value of t_aip_scope_info.CREATE_STAFF
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public String getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aip_scope_info.CREATE_STAFF
     *
     * @param createStaff the value for t_aip_scope_info.CREATE_STAFF
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public void setCreateStaff(String createStaff) {
        this.createStaff = createStaff == null ? null : createStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aip_scope_info.UPDATE_TIME
     *
     * @return the value of t_aip_scope_info.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aip_scope_info.UPDATE_TIME
     *
     * @param updateTime the value for t_aip_scope_info.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aip_scope_info.UPDATE_STAFF
     *
     * @return the value of t_aip_scope_info.UPDATE_STAFF
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public String getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aip_scope_info.UPDATE_STAFF
     *
     * @param updateStaff the value for t_aip_scope_info.UPDATE_STAFF
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public void setUpdateStaff(String updateStaff) {
        this.updateStaff = updateStaff == null ? null : updateStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aip_scope_info.TYPE
     *
     * @return the value of t_aip_scope_info.TYPE
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aip_scope_info.TYPE
     *
     * @param type the value for t_aip_scope_info.TYPE
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aip_scope_info.SERVICE_ID
     *
     * @return the value of t_aip_scope_info.SERVICE_ID
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aip_scope_info.SERVICE_ID
     *
     * @param serviceId the value for t_aip_scope_info.SERVICE_ID
     *
     * @mbg.generated Mon Apr 24 10:27:08 CST 2017
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId == null ? null : serviceId.trim();
    }
}