package com.ai.bdex.dataexchange.tradecenter.dao.model;

import java.util.Date;

public class GdsInfo2Prop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gds_info_2_prop.gp_id
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    private Integer gpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gds_info_2_prop.gds_id
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    private Integer gdsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gds_info_2_prop.pro_id
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gds_info_2_prop.pro_type
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    private String proType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gds_info_2_prop.pro_name
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    private String proName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gds_info_2_prop.pro_value
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    private String proValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gds_info_2_prop.show_order
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    private Integer showOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gds_info_2_prop.status
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gds_info_2_prop.create_user
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gds_info_2_prop.create_time
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gds_info_2_prop.update_user
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gds_info_2_prop.update_time
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gds_info_2_prop.gp_id
     *
     * @return the value of t_gds_info_2_prop.gp_id
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public Integer getGpId() {
        return gpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gds_info_2_prop.gp_id
     *
     * @param gpId the value for t_gds_info_2_prop.gp_id
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public void setGpId(Integer gpId) {
        this.gpId = gpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gds_info_2_prop.gds_id
     *
     * @return the value of t_gds_info_2_prop.gds_id
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public Integer getGdsId() {
        return gdsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gds_info_2_prop.gds_id
     *
     * @param gdsId the value for t_gds_info_2_prop.gds_id
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public void setGdsId(Integer gdsId) {
        this.gdsId = gdsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gds_info_2_prop.pro_id
     *
     * @return the value of t_gds_info_2_prop.pro_id
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gds_info_2_prop.pro_id
     *
     * @param proId the value for t_gds_info_2_prop.pro_id
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gds_info_2_prop.pro_type
     *
     * @return the value of t_gds_info_2_prop.pro_type
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public String getProType() {
        return proType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gds_info_2_prop.pro_type
     *
     * @param proType the value for t_gds_info_2_prop.pro_type
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public void setProType(String proType) {
        this.proType = proType == null ? null : proType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gds_info_2_prop.pro_name
     *
     * @return the value of t_gds_info_2_prop.pro_name
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gds_info_2_prop.pro_name
     *
     * @param proName the value for t_gds_info_2_prop.pro_name
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gds_info_2_prop.pro_value
     *
     * @return the value of t_gds_info_2_prop.pro_value
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public String getProValue() {
        return proValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gds_info_2_prop.pro_value
     *
     * @param proValue the value for t_gds_info_2_prop.pro_value
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public void setProValue(String proValue) {
        this.proValue = proValue == null ? null : proValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gds_info_2_prop.show_order
     *
     * @return the value of t_gds_info_2_prop.show_order
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public Integer getShowOrder() {
        return showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gds_info_2_prop.show_order
     *
     * @param showOrder the value for t_gds_info_2_prop.show_order
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gds_info_2_prop.status
     *
     * @return the value of t_gds_info_2_prop.status
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gds_info_2_prop.status
     *
     * @param status the value for t_gds_info_2_prop.status
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gds_info_2_prop.create_user
     *
     * @return the value of t_gds_info_2_prop.create_user
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gds_info_2_prop.create_user
     *
     * @param createUser the value for t_gds_info_2_prop.create_user
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gds_info_2_prop.create_time
     *
     * @return the value of t_gds_info_2_prop.create_time
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gds_info_2_prop.create_time
     *
     * @param createTime the value for t_gds_info_2_prop.create_time
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gds_info_2_prop.update_user
     *
     * @return the value of t_gds_info_2_prop.update_user
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gds_info_2_prop.update_user
     *
     * @param updateUser the value for t_gds_info_2_prop.update_user
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gds_info_2_prop.update_time
     *
     * @return the value of t_gds_info_2_prop.update_time
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gds_info_2_prop.update_time
     *
     * @param updateTime the value for t_gds_info_2_prop.update_time
     *
     * @mbg.generated Tue Apr 18 14:57:17 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}