package com.ai.bdex.dataexchange.tradecenter.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrdLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.SYS_LOG_ID
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private Long sysLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.ORDER_ID
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.SUB_ORDER
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String subOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.NODE
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String node;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.NODE_DESC
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String nodeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.NEXD1
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private BigDecimal nexd1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.RESERVED1
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String reserved1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.RESERVED2
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String reserved2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.RESERVED3
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String reserved3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.REMARK
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.PROVINCE_CODE
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.CREATE_STAFF
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_log.CREATE_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.SYS_LOG_ID
     *
     * @return the value of t_ord_log.SYS_LOG_ID
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public Long getSysLogId() {
        return sysLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.SYS_LOG_ID
     *
     * @param sysLogId the value for t_ord_log.SYS_LOG_ID
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setSysLogId(Long sysLogId) {
        this.sysLogId = sysLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.ORDER_ID
     *
     * @return the value of t_ord_log.ORDER_ID
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.ORDER_ID
     *
     * @param orderId the value for t_ord_log.ORDER_ID
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.SUB_ORDER
     *
     * @return the value of t_ord_log.SUB_ORDER
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getSubOrder() {
        return subOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.SUB_ORDER
     *
     * @param subOrder the value for t_ord_log.SUB_ORDER
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setSubOrder(String subOrder) {
        this.subOrder = subOrder == null ? null : subOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.NODE
     *
     * @return the value of t_ord_log.NODE
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getNode() {
        return node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.NODE
     *
     * @param node the value for t_ord_log.NODE
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setNode(String node) {
        this.node = node == null ? null : node.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.NODE_DESC
     *
     * @return the value of t_ord_log.NODE_DESC
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getNodeDesc() {
        return nodeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.NODE_DESC
     *
     * @param nodeDesc the value for t_ord_log.NODE_DESC
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setNodeDesc(String nodeDesc) {
        this.nodeDesc = nodeDesc == null ? null : nodeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.NEXD1
     *
     * @return the value of t_ord_log.NEXD1
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public BigDecimal getNexd1() {
        return nexd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.NEXD1
     *
     * @param nexd1 the value for t_ord_log.NEXD1
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setNexd1(BigDecimal nexd1) {
        this.nexd1 = nexd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.RESERVED1
     *
     * @return the value of t_ord_log.RESERVED1
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.RESERVED1
     *
     * @param reserved1 the value for t_ord_log.RESERVED1
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.RESERVED2
     *
     * @return the value of t_ord_log.RESERVED2
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.RESERVED2
     *
     * @param reserved2 the value for t_ord_log.RESERVED2
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.RESERVED3
     *
     * @return the value of t_ord_log.RESERVED3
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.RESERVED3
     *
     * @param reserved3 the value for t_ord_log.RESERVED3
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.REMARK
     *
     * @return the value of t_ord_log.REMARK
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.REMARK
     *
     * @param remark the value for t_ord_log.REMARK
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.PROVINCE_CODE
     *
     * @return the value of t_ord_log.PROVINCE_CODE
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.PROVINCE_CODE
     *
     * @param provinceCode the value for t_ord_log.PROVINCE_CODE
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.CREATE_STAFF
     *
     * @return the value of t_ord_log.CREATE_STAFF
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.CREATE_STAFF
     *
     * @param createStaff the value for t_ord_log.CREATE_STAFF
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setCreateStaff(String createStaff) {
        this.createStaff = createStaff == null ? null : createStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_log.CREATE_TIME
     *
     * @return the value of t_ord_log.CREATE_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_log.CREATE_TIME
     *
     * @param createTime the value for t_ord_log.CREATE_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}