package com.ai.bdex.dataexchange.tradecenter.dao.model;

import java.util.Date;

public class OrdTimeLimit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_time_limit.TIME_LIMIT_NO
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private Long timeLimitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_time_limit.PROVINCE_CODE
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_time_limit.CANCEL_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private Long cancelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_time_limit.CAT_ID
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private Long catId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_time_limit.LIMIT_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private Long limitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_time_limit.IS_VALID
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_time_limit.IS_ACTIVITY
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String isActivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_time_limit.CREATE_STAFF
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_time_limit.CREATE_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_time_limit.UPDATE_STAFF
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private String updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_time_limit.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_time_limit.TIME_LIMIT_NO
     *
     * @return the value of t_ord_time_limit.TIME_LIMIT_NO
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public Long getTimeLimitNo() {
        return timeLimitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_time_limit.TIME_LIMIT_NO
     *
     * @param timeLimitNo the value for t_ord_time_limit.TIME_LIMIT_NO
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setTimeLimitNo(Long timeLimitNo) {
        this.timeLimitNo = timeLimitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_time_limit.PROVINCE_CODE
     *
     * @return the value of t_ord_time_limit.PROVINCE_CODE
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_time_limit.PROVINCE_CODE
     *
     * @param provinceCode the value for t_ord_time_limit.PROVINCE_CODE
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_time_limit.CANCEL_TIME
     *
     * @return the value of t_ord_time_limit.CANCEL_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public Long getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_time_limit.CANCEL_TIME
     *
     * @param cancelTime the value for t_ord_time_limit.CANCEL_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setCancelTime(Long cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_time_limit.CAT_ID
     *
     * @return the value of t_ord_time_limit.CAT_ID
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public Long getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_time_limit.CAT_ID
     *
     * @param catId the value for t_ord_time_limit.CAT_ID
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setCatId(Long catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_time_limit.LIMIT_TIME
     *
     * @return the value of t_ord_time_limit.LIMIT_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public Long getLimitTime() {
        return limitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_time_limit.LIMIT_TIME
     *
     * @param limitTime the value for t_ord_time_limit.LIMIT_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setLimitTime(Long limitTime) {
        this.limitTime = limitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_time_limit.IS_VALID
     *
     * @return the value of t_ord_time_limit.IS_VALID
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_time_limit.IS_VALID
     *
     * @param isValid the value for t_ord_time_limit.IS_VALID
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_time_limit.IS_ACTIVITY
     *
     * @return the value of t_ord_time_limit.IS_ACTIVITY
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getIsActivity() {
        return isActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_time_limit.IS_ACTIVITY
     *
     * @param isActivity the value for t_ord_time_limit.IS_ACTIVITY
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setIsActivity(String isActivity) {
        this.isActivity = isActivity == null ? null : isActivity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_time_limit.CREATE_STAFF
     *
     * @return the value of t_ord_time_limit.CREATE_STAFF
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_time_limit.CREATE_STAFF
     *
     * @param createStaff the value for t_ord_time_limit.CREATE_STAFF
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setCreateStaff(String createStaff) {
        this.createStaff = createStaff == null ? null : createStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_time_limit.CREATE_TIME
     *
     * @return the value of t_ord_time_limit.CREATE_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_time_limit.CREATE_TIME
     *
     * @param createTime the value for t_ord_time_limit.CREATE_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_time_limit.UPDATE_STAFF
     *
     * @return the value of t_ord_time_limit.UPDATE_STAFF
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public String getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_time_limit.UPDATE_STAFF
     *
     * @param updateStaff the value for t_ord_time_limit.UPDATE_STAFF
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setUpdateStaff(String updateStaff) {
        this.updateStaff = updateStaff == null ? null : updateStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_time_limit.UPDATE_TIME
     *
     * @return the value of t_ord_time_limit.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_time_limit.UPDATE_TIME
     *
     * @param updateTime the value for t_ord_time_limit.UPDATE_TIME
     *
     * @mbg.generated Mon Apr 17 21:03:39 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}