package com.ai.bdex.dataexchange.tradecenter.dao.model;

import java.util.Date;

public class PageModuleAdProp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page_modular_ad_prop.ATTR_ID
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    private Integer attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page_modular_ad_prop.MODULE_ID
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    private String moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page_modular_ad_prop.show_count
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    private Integer showCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page_modular_ad_prop.PIC_MEASURE
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    private String picMeasure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page_modular_ad_prop.PIC_SIZE
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    private String picSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page_modular_ad_prop.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page_modular_ad_prop.status
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page_modular_ad_prop.REMARK
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page_modular_ad_prop.CREATE_STAFF_ID
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    private String createStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page_modular_ad_prop.CREATE_TIME2
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    private Date createTime2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_page_modular_ad_prop.UPDATE_STAFF_ID
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    private String updateStaffId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page_modular_ad_prop.ATTR_ID
     *
     * @return the value of t_page_modular_ad_prop.ATTR_ID
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public Integer getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page_modular_ad_prop.ATTR_ID
     *
     * @param attrId the value for t_page_modular_ad_prop.ATTR_ID
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public void setAttrId(Integer attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page_modular_ad_prop.MODULE_ID
     *
     * @return the value of t_page_modular_ad_prop.MODULE_ID
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page_modular_ad_prop.MODULE_ID
     *
     * @param moduleId the value for t_page_modular_ad_prop.MODULE_ID
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page_modular_ad_prop.show_count
     *
     * @return the value of t_page_modular_ad_prop.show_count
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public Integer getShowCount() {
        return showCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page_modular_ad_prop.show_count
     *
     * @param showCount the value for t_page_modular_ad_prop.show_count
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public void setShowCount(Integer showCount) {
        this.showCount = showCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page_modular_ad_prop.PIC_MEASURE
     *
     * @return the value of t_page_modular_ad_prop.PIC_MEASURE
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public String getPicMeasure() {
        return picMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page_modular_ad_prop.PIC_MEASURE
     *
     * @param picMeasure the value for t_page_modular_ad_prop.PIC_MEASURE
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public void setPicMeasure(String picMeasure) {
        this.picMeasure = picMeasure == null ? null : picMeasure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page_modular_ad_prop.PIC_SIZE
     *
     * @return the value of t_page_modular_ad_prop.PIC_SIZE
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public String getPicSize() {
        return picSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page_modular_ad_prop.PIC_SIZE
     *
     * @param picSize the value for t_page_modular_ad_prop.PIC_SIZE
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public void setPicSize(String picSize) {
        this.picSize = picSize == null ? null : picSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page_modular_ad_prop.UPDATE_TIME
     *
     * @return the value of t_page_modular_ad_prop.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page_modular_ad_prop.UPDATE_TIME
     *
     * @param updateTime the value for t_page_modular_ad_prop.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page_modular_ad_prop.status
     *
     * @return the value of t_page_modular_ad_prop.status
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page_modular_ad_prop.status
     *
     * @param status the value for t_page_modular_ad_prop.status
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page_modular_ad_prop.REMARK
     *
     * @return the value of t_page_modular_ad_prop.REMARK
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page_modular_ad_prop.REMARK
     *
     * @param remark the value for t_page_modular_ad_prop.REMARK
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page_modular_ad_prop.CREATE_STAFF_ID
     *
     * @return the value of t_page_modular_ad_prop.CREATE_STAFF_ID
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public String getCreateStaffId() {
        return createStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page_modular_ad_prop.CREATE_STAFF_ID
     *
     * @param createStaffId the value for t_page_modular_ad_prop.CREATE_STAFF_ID
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public void setCreateStaffId(String createStaffId) {
        this.createStaffId = createStaffId == null ? null : createStaffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page_modular_ad_prop.CREATE_TIME2
     *
     * @return the value of t_page_modular_ad_prop.CREATE_TIME2
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public Date getCreateTime2() {
        return createTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page_modular_ad_prop.CREATE_TIME2
     *
     * @param createTime2 the value for t_page_modular_ad_prop.CREATE_TIME2
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public void setCreateTime2(Date createTime2) {
        this.createTime2 = createTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_page_modular_ad_prop.UPDATE_STAFF_ID
     *
     * @return the value of t_page_modular_ad_prop.UPDATE_STAFF_ID
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public String getUpdateStaffId() {
        return updateStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_page_modular_ad_prop.UPDATE_STAFF_ID
     *
     * @param updateStaffId the value for t_page_modular_ad_prop.UPDATE_STAFF_ID
     *
     * @mbg.generated Tue Apr 18 20:28:29 CST 2017
     */
    public void setUpdateStaffId(String updateStaffId) {
        this.updateStaffId = updateStaffId == null ? null : updateStaffId.trim();
    }
}