package com.ai.bdex.dataexchange.tradecenter.dao.model;

import java.util.Date;

public class PayQuartzInfoLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.ORIGINAL_ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Long originalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.TASK_TYPE
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private String taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.ORDER_ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.SUB_ORDER
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private String subOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.STAFF_ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Long staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.DEAL_FLAG
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private String dealFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.ERROR_TIMES
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Integer errorTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.CREATE_STAFF
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Long createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.CREATE_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.NEXT_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Date nextTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.UPDATE_STAFF
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Long updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_quartz_info_log.LOG_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Date logTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.ID
     *
     * @return the value of t_pay_quartz_info_log.ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.ID
     *
     * @param id the value for t_pay_quartz_info_log.ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.ORIGINAL_ID
     *
     * @return the value of t_pay_quartz_info_log.ORIGINAL_ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Long getOriginalId() {
        return originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.ORIGINAL_ID
     *
     * @param originalId the value for t_pay_quartz_info_log.ORIGINAL_ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setOriginalId(Long originalId) {
        this.originalId = originalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.TASK_TYPE
     *
     * @return the value of t_pay_quartz_info_log.TASK_TYPE
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.TASK_TYPE
     *
     * @param taskType the value for t_pay_quartz_info_log.TASK_TYPE
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType == null ? null : taskType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.ORDER_ID
     *
     * @return the value of t_pay_quartz_info_log.ORDER_ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.ORDER_ID
     *
     * @param orderId the value for t_pay_quartz_info_log.ORDER_ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.SUB_ORDER
     *
     * @return the value of t_pay_quartz_info_log.SUB_ORDER
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public String getSubOrder() {
        return subOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.SUB_ORDER
     *
     * @param subOrder the value for t_pay_quartz_info_log.SUB_ORDER
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setSubOrder(String subOrder) {
        this.subOrder = subOrder == null ? null : subOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.STAFF_ID
     *
     * @return the value of t_pay_quartz_info_log.STAFF_ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Long getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.STAFF_ID
     *
     * @param staffId the value for t_pay_quartz_info_log.STAFF_ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.DEAL_FLAG
     *
     * @return the value of t_pay_quartz_info_log.DEAL_FLAG
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public String getDealFlag() {
        return dealFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.DEAL_FLAG
     *
     * @param dealFlag the value for t_pay_quartz_info_log.DEAL_FLAG
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setDealFlag(String dealFlag) {
        this.dealFlag = dealFlag == null ? null : dealFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.ERROR_TIMES
     *
     * @return the value of t_pay_quartz_info_log.ERROR_TIMES
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Integer getErrorTimes() {
        return errorTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.ERROR_TIMES
     *
     * @param errorTimes the value for t_pay_quartz_info_log.ERROR_TIMES
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setErrorTimes(Integer errorTimes) {
        this.errorTimes = errorTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.CREATE_STAFF
     *
     * @return the value of t_pay_quartz_info_log.CREATE_STAFF
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Long getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.CREATE_STAFF
     *
     * @param createStaff the value for t_pay_quartz_info_log.CREATE_STAFF
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setCreateStaff(Long createStaff) {
        this.createStaff = createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.CREATE_TIME
     *
     * @return the value of t_pay_quartz_info_log.CREATE_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.CREATE_TIME
     *
     * @param createTime the value for t_pay_quartz_info_log.CREATE_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.NEXT_TIME
     *
     * @return the value of t_pay_quartz_info_log.NEXT_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Date getNextTime() {
        return nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.NEXT_TIME
     *
     * @param nextTime the value for t_pay_quartz_info_log.NEXT_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.UPDATE_STAFF
     *
     * @return the value of t_pay_quartz_info_log.UPDATE_STAFF
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Long getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.UPDATE_STAFF
     *
     * @param updateStaff the value for t_pay_quartz_info_log.UPDATE_STAFF
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setUpdateStaff(Long updateStaff) {
        this.updateStaff = updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.UPDATE_TIME
     *
     * @return the value of t_pay_quartz_info_log.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.UPDATE_TIME
     *
     * @param updateTime the value for t_pay_quartz_info_log.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_quartz_info_log.LOG_TIME
     *
     * @return the value of t_pay_quartz_info_log.LOG_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_quartz_info_log.LOG_TIME
     *
     * @param logTime the value for t_pay_quartz_info_log.LOG_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }
}