package com.ai.bdex.dataexchange.tradecenter.dao.model;

import java.util.Date;

public class PayRepeat extends PayRepeatKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_repeat.ORDER_ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_repeat.PAY_WAY_NAME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private String payWayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_repeat.PAYMENT
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Long payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_repeat.PAY_STATUS
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private String payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_repeat.PAY_DESC
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private String payDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_repeat.PAY_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_repeat.MERCH_ACCT
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private String merchAcct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_repeat.PAYEE_NAME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private String payeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_repeat.PAYEE_ACCT
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private String payeeAcct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_repeat.CREATE_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_repeat.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_repeat.ORDER_ID
     *
     * @return the value of t_pay_repeat.ORDER_ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_repeat.ORDER_ID
     *
     * @param orderId the value for t_pay_repeat.ORDER_ID
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_repeat.PAY_WAY_NAME
     *
     * @return the value of t_pay_repeat.PAY_WAY_NAME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public String getPayWayName() {
        return payWayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_repeat.PAY_WAY_NAME
     *
     * @param payWayName the value for t_pay_repeat.PAY_WAY_NAME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setPayWayName(String payWayName) {
        this.payWayName = payWayName == null ? null : payWayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_repeat.PAYMENT
     *
     * @return the value of t_pay_repeat.PAYMENT
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Long getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_repeat.PAYMENT
     *
     * @param payment the value for t_pay_repeat.PAYMENT
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setPayment(Long payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_repeat.PAY_STATUS
     *
     * @return the value of t_pay_repeat.PAY_STATUS
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_repeat.PAY_STATUS
     *
     * @param payStatus the value for t_pay_repeat.PAY_STATUS
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_repeat.PAY_DESC
     *
     * @return the value of t_pay_repeat.PAY_DESC
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public String getPayDesc() {
        return payDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_repeat.PAY_DESC
     *
     * @param payDesc the value for t_pay_repeat.PAY_DESC
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setPayDesc(String payDesc) {
        this.payDesc = payDesc == null ? null : payDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_repeat.PAY_TIME
     *
     * @return the value of t_pay_repeat.PAY_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_repeat.PAY_TIME
     *
     * @param payTime the value for t_pay_repeat.PAY_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_repeat.MERCH_ACCT
     *
     * @return the value of t_pay_repeat.MERCH_ACCT
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public String getMerchAcct() {
        return merchAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_repeat.MERCH_ACCT
     *
     * @param merchAcct the value for t_pay_repeat.MERCH_ACCT
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setMerchAcct(String merchAcct) {
        this.merchAcct = merchAcct == null ? null : merchAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_repeat.PAYEE_NAME
     *
     * @return the value of t_pay_repeat.PAYEE_NAME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public String getPayeeName() {
        return payeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_repeat.PAYEE_NAME
     *
     * @param payeeName the value for t_pay_repeat.PAYEE_NAME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setPayeeName(String payeeName) {
        this.payeeName = payeeName == null ? null : payeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_repeat.PAYEE_ACCT
     *
     * @return the value of t_pay_repeat.PAYEE_ACCT
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public String getPayeeAcct() {
        return payeeAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_repeat.PAYEE_ACCT
     *
     * @param payeeAcct the value for t_pay_repeat.PAYEE_ACCT
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setPayeeAcct(String payeeAcct) {
        this.payeeAcct = payeeAcct == null ? null : payeeAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_repeat.CREATE_TIME
     *
     * @return the value of t_pay_repeat.CREATE_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_repeat.CREATE_TIME
     *
     * @param createTime the value for t_pay_repeat.CREATE_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_repeat.UPDATE_TIME
     *
     * @return the value of t_pay_repeat.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_repeat.UPDATE_TIME
     *
     * @param updateTime the value for t_pay_repeat.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 18 14:56:53 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}