package com.ai.bdex.dataexchange.apigateway.dubbo.dto;

import java.io.Serializable;
import java.util.Date;

public class AipClientLoginLogDTO implements Serializable{
	private static final long serialVersionUID = 1L;
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_aip_client_login_log.LOG_ID
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   private String logId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_aip_client_login_log.CLIENT_ID
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   private String clientId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_aip_client_login_log.IN_TIME
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   private Date inTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_aip_client_login_log.IN_IP
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   private String inIp;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_aip_client_login_log.REFRESH_TOKEN
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   private String refreshToken;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_aip_client_login_log.REFRESH_TOKEN_EXPIRES
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   private Date refreshTokenExpires;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_aip_client_login_log.UPDATE_TIME
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   private Date updateTime;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_aip_client_login_log.LOG_ID
    *
    * @return the value of t_aip_client_login_log.LOG_ID
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public String getLogId() {
       return logId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_aip_client_login_log.LOG_ID
    *
    * @param logId the value for t_aip_client_login_log.LOG_ID
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public void setLogId(String logId) {
       this.logId = logId == null ? null : logId.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_aip_client_login_log.CLIENT_ID
    *
    * @return the value of t_aip_client_login_log.CLIENT_ID
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public String getClientId() {
       return clientId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_aip_client_login_log.CLIENT_ID
    *
    * @param clientId the value for t_aip_client_login_log.CLIENT_ID
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public void setClientId(String clientId) {
       this.clientId = clientId == null ? null : clientId.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_aip_client_login_log.IN_TIME
    *
    * @return the value of t_aip_client_login_log.IN_TIME
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public Date getInTime() {
       return inTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_aip_client_login_log.IN_TIME
    *
    * @param inTime the value for t_aip_client_login_log.IN_TIME
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public void setInTime(Date inTime) {
       this.inTime = inTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_aip_client_login_log.IN_IP
    *
    * @return the value of t_aip_client_login_log.IN_IP
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public String getInIp() {
       return inIp;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_aip_client_login_log.IN_IP
    *
    * @param inIp the value for t_aip_client_login_log.IN_IP
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public void setInIp(String inIp) {
       this.inIp = inIp == null ? null : inIp.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_aip_client_login_log.REFRESH_TOKEN
    *
    * @return the value of t_aip_client_login_log.REFRESH_TOKEN
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public String getRefreshToken() {
       return refreshToken;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_aip_client_login_log.REFRESH_TOKEN
    *
    * @param refreshToken the value for t_aip_client_login_log.REFRESH_TOKEN
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public void setRefreshToken(String refreshToken) {
       this.refreshToken = refreshToken == null ? null : refreshToken.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_aip_client_login_log.REFRESH_TOKEN_EXPIRES
    *
    * @return the value of t_aip_client_login_log.REFRESH_TOKEN_EXPIRES
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public Date getRefreshTokenExpires() {
       return refreshTokenExpires;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_aip_client_login_log.REFRESH_TOKEN_EXPIRES
    *
    * @param refreshTokenExpires the value for t_aip_client_login_log.REFRESH_TOKEN_EXPIRES
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public void setRefreshTokenExpires(Date refreshTokenExpires) {
       this.refreshTokenExpires = refreshTokenExpires;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_aip_client_login_log.UPDATE_TIME
    *
    * @return the value of t_aip_client_login_log.UPDATE_TIME
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public Date getUpdateTime() {
       return updateTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_aip_client_login_log.UPDATE_TIME
    *
    * @param updateTime the value for t_aip_client_login_log.UPDATE_TIME
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public void setUpdateTime(Date updateTime) {
       this.updateTime = updateTime;
   }
}
