package com.ai.bdex.dataexchange.apigateway.dubbo.dto;

import java.io.Serializable;
import java.util.Date;

public class AipClientRefreshtokenDTO implements Serializable{
	private static final long serialVersionUID = 1L;
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_aip_client_refreshtoken.REFRESH_TOKEN
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   private String refreshToken;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_aip_client_refreshtoken.CLIENT_ID
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   private String clientId;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_aip_client_refreshtoken.EXPIRES_IN
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   private Date expiresIn;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_aip_client_refreshtoken.CREATE_TIME
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   private Date createTime;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_aip_client_refreshtoken.UPDATE_TIME
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   private Date updateTime;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_aip_client_refreshtoken.REFRESH_TOKEN
    *
    * @return the value of t_aip_client_refreshtoken.REFRESH_TOKEN
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public String getRefreshToken() {
       return refreshToken;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_aip_client_refreshtoken.REFRESH_TOKEN
    *
    * @param refreshToken the value for t_aip_client_refreshtoken.REFRESH_TOKEN
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public void setRefreshToken(String refreshToken) {
       this.refreshToken = refreshToken == null ? null : refreshToken.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_aip_client_refreshtoken.CLIENT_ID
    *
    * @return the value of t_aip_client_refreshtoken.CLIENT_ID
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public String getClientId() {
       return clientId;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_aip_client_refreshtoken.CLIENT_ID
    *
    * @param clientId the value for t_aip_client_refreshtoken.CLIENT_ID
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public void setClientId(String clientId) {
       this.clientId = clientId == null ? null : clientId.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_aip_client_refreshtoken.EXPIRES_IN
    *
    * @return the value of t_aip_client_refreshtoken.EXPIRES_IN
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public Date getExpiresIn() {
       return expiresIn;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_aip_client_refreshtoken.EXPIRES_IN
    *
    * @param expiresIn the value for t_aip_client_refreshtoken.EXPIRES_IN
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public void setExpiresIn(Date expiresIn) {
       this.expiresIn = expiresIn;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_aip_client_refreshtoken.CREATE_TIME
    *
    * @return the value of t_aip_client_refreshtoken.CREATE_TIME
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public Date getCreateTime() {
       return createTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_aip_client_refreshtoken.CREATE_TIME
    *
    * @param createTime the value for t_aip_client_refreshtoken.CREATE_TIME
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public void setCreateTime(Date createTime) {
       this.createTime = createTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column t_aip_client_refreshtoken.UPDATE_TIME
    *
    * @return the value of t_aip_client_refreshtoken.UPDATE_TIME
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public Date getUpdateTime() {
       return updateTime;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column t_aip_client_refreshtoken.UPDATE_TIME
    *
    * @param updateTime the value for t_aip_client_refreshtoken.UPDATE_TIME
    *
    * @mbg.generated Mon Apr 24 10:27:08 CST 2017
    */
   public void setUpdateTime(Date updateTime) {
       this.updateTime = updateTime;
   }
}
