package com.ai.bdex.dataexchange.report.dao.model;

import java.util.Date;

public class OrdInvoiceTax {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.ORDER_TAX_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private Long orderTaxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.TAX_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private Long taxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.ORDER_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.STAFF_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.SHOP_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.INVOICE_TITLE
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String invoiceTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.TAXPAYER_NO
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String taxpayerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.CONTACT_INFO
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String contactInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.PHONE
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.BANK_NAME
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.ACCT_INFO
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String acctInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.VFS_ID1
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String vfsId1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.VFS_ID2
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String vfsId2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.VFS_ID3
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String vfsId3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.VFS_ID4
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String vfsId4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.STATUS
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.PROVINCE_CODE
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String provinceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.CREATE_STAFF
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String createStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.CREATE_TIME
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.UPDATE_STAFF
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String updateStaff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.UPDATE_TIME
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.INVOICE_DESC
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String invoiceDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.SEND_ADDR
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String sendAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.APPLY_MONEY
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private Long applyMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ord_invoice_tax.INVOICE_TYPE
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    private String invoiceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.ORDER_TAX_ID
     *
     * @return the value of t_ord_invoice_tax.ORDER_TAX_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public Long getOrderTaxId() {
        return orderTaxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.ORDER_TAX_ID
     *
     * @param orderTaxId the value for t_ord_invoice_tax.ORDER_TAX_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setOrderTaxId(Long orderTaxId) {
        this.orderTaxId = orderTaxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.TAX_ID
     *
     * @return the value of t_ord_invoice_tax.TAX_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public Long getTaxId() {
        return taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.TAX_ID
     *
     * @param taxId the value for t_ord_invoice_tax.TAX_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setTaxId(Long taxId) {
        this.taxId = taxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.ORDER_ID
     *
     * @return the value of t_ord_invoice_tax.ORDER_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.ORDER_ID
     *
     * @param orderId the value for t_ord_invoice_tax.ORDER_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.STAFF_ID
     *
     * @return the value of t_ord_invoice_tax.STAFF_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.STAFF_ID
     *
     * @param staffId the value for t_ord_invoice_tax.STAFF_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.SHOP_ID
     *
     * @return the value of t_ord_invoice_tax.SHOP_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.SHOP_ID
     *
     * @param shopId the value for t_ord_invoice_tax.SHOP_ID
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.INVOICE_TITLE
     *
     * @return the value of t_ord_invoice_tax.INVOICE_TITLE
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.INVOICE_TITLE
     *
     * @param invoiceTitle the value for t_ord_invoice_tax.INVOICE_TITLE
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.TAXPAYER_NO
     *
     * @return the value of t_ord_invoice_tax.TAXPAYER_NO
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getTaxpayerNo() {
        return taxpayerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.TAXPAYER_NO
     *
     * @param taxpayerNo the value for t_ord_invoice_tax.TAXPAYER_NO
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setTaxpayerNo(String taxpayerNo) {
        this.taxpayerNo = taxpayerNo == null ? null : taxpayerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.CONTACT_INFO
     *
     * @return the value of t_ord_invoice_tax.CONTACT_INFO
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getContactInfo() {
        return contactInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.CONTACT_INFO
     *
     * @param contactInfo the value for t_ord_invoice_tax.CONTACT_INFO
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setContactInfo(String contactInfo) {
        this.contactInfo = contactInfo == null ? null : contactInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.PHONE
     *
     * @return the value of t_ord_invoice_tax.PHONE
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.PHONE
     *
     * @param phone the value for t_ord_invoice_tax.PHONE
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.BANK_NAME
     *
     * @return the value of t_ord_invoice_tax.BANK_NAME
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.BANK_NAME
     *
     * @param bankName the value for t_ord_invoice_tax.BANK_NAME
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.ACCT_INFO
     *
     * @return the value of t_ord_invoice_tax.ACCT_INFO
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getAcctInfo() {
        return acctInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.ACCT_INFO
     *
     * @param acctInfo the value for t_ord_invoice_tax.ACCT_INFO
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setAcctInfo(String acctInfo) {
        this.acctInfo = acctInfo == null ? null : acctInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.VFS_ID1
     *
     * @return the value of t_ord_invoice_tax.VFS_ID1
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getVfsId1() {
        return vfsId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.VFS_ID1
     *
     * @param vfsId1 the value for t_ord_invoice_tax.VFS_ID1
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setVfsId1(String vfsId1) {
        this.vfsId1 = vfsId1 == null ? null : vfsId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.VFS_ID2
     *
     * @return the value of t_ord_invoice_tax.VFS_ID2
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getVfsId2() {
        return vfsId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.VFS_ID2
     *
     * @param vfsId2 the value for t_ord_invoice_tax.VFS_ID2
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setVfsId2(String vfsId2) {
        this.vfsId2 = vfsId2 == null ? null : vfsId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.VFS_ID3
     *
     * @return the value of t_ord_invoice_tax.VFS_ID3
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getVfsId3() {
        return vfsId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.VFS_ID3
     *
     * @param vfsId3 the value for t_ord_invoice_tax.VFS_ID3
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setVfsId3(String vfsId3) {
        this.vfsId3 = vfsId3 == null ? null : vfsId3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.VFS_ID4
     *
     * @return the value of t_ord_invoice_tax.VFS_ID4
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getVfsId4() {
        return vfsId4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.VFS_ID4
     *
     * @param vfsId4 the value for t_ord_invoice_tax.VFS_ID4
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setVfsId4(String vfsId4) {
        this.vfsId4 = vfsId4 == null ? null : vfsId4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.STATUS
     *
     * @return the value of t_ord_invoice_tax.STATUS
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.STATUS
     *
     * @param status the value for t_ord_invoice_tax.STATUS
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.PROVINCE_CODE
     *
     * @return the value of t_ord_invoice_tax.PROVINCE_CODE
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.PROVINCE_CODE
     *
     * @param provinceCode the value for t_ord_invoice_tax.PROVINCE_CODE
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.CREATE_STAFF
     *
     * @return the value of t_ord_invoice_tax.CREATE_STAFF
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.CREATE_STAFF
     *
     * @param createStaff the value for t_ord_invoice_tax.CREATE_STAFF
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setCreateStaff(String createStaff) {
        this.createStaff = createStaff == null ? null : createStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.CREATE_TIME
     *
     * @return the value of t_ord_invoice_tax.CREATE_TIME
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.CREATE_TIME
     *
     * @param createTime the value for t_ord_invoice_tax.CREATE_TIME
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.UPDATE_STAFF
     *
     * @return the value of t_ord_invoice_tax.UPDATE_STAFF
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.UPDATE_STAFF
     *
     * @param updateStaff the value for t_ord_invoice_tax.UPDATE_STAFF
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setUpdateStaff(String updateStaff) {
        this.updateStaff = updateStaff == null ? null : updateStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.UPDATE_TIME
     *
     * @return the value of t_ord_invoice_tax.UPDATE_TIME
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.UPDATE_TIME
     *
     * @param updateTime the value for t_ord_invoice_tax.UPDATE_TIME
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.INVOICE_DESC
     *
     * @return the value of t_ord_invoice_tax.INVOICE_DESC
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getInvoiceDesc() {
        return invoiceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.INVOICE_DESC
     *
     * @param invoiceDesc the value for t_ord_invoice_tax.INVOICE_DESC
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setInvoiceDesc(String invoiceDesc) {
        this.invoiceDesc = invoiceDesc == null ? null : invoiceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.SEND_ADDR
     *
     * @return the value of t_ord_invoice_tax.SEND_ADDR
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getSendAddr() {
        return sendAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.SEND_ADDR
     *
     * @param sendAddr the value for t_ord_invoice_tax.SEND_ADDR
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setSendAddr(String sendAddr) {
        this.sendAddr = sendAddr == null ? null : sendAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.APPLY_MONEY
     *
     * @return the value of t_ord_invoice_tax.APPLY_MONEY
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public Long getApplyMoney() {
        return applyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.APPLY_MONEY
     *
     * @param applyMoney the value for t_ord_invoice_tax.APPLY_MONEY
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setApplyMoney(Long applyMoney) {
        this.applyMoney = applyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ord_invoice_tax.INVOICE_TYPE
     *
     * @return the value of t_ord_invoice_tax.INVOICE_TYPE
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public String getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ord_invoice_tax.INVOICE_TYPE
     *
     * @param invoiceType the value for t_ord_invoice_tax.INVOICE_TYPE
     *
     * @mbg.generated Tue Jun 06 11:35:49 CST 2017
     */
    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType == null ? null : invoiceType.trim();
    }
}