server:
  port: 8082

spring:
  session:
    store-type: none

  dubbo:
    appname: manager-web
    registry: zookeeper://127.0.0.1:2181
    protocol: dubbo
    group: devGroup

application:
  cache:
    confpath: /com/ai/paas/cache/conf
  session:
    confpath: /com/ai/paas/session/conf
  image:
    confpath: /com/ai/paas/image/conf
  file:
    confpath: /com/ai/paas/file/conf
