server:
  port: 8082

spring:
  session:
    store-type: none
  dubbo:
    application:
      name: manage-web
      owner: zhaoyf7
      environment: develop
    registry:
      address: 127.0.0.1:2181
    provider:
      enabled: false
    consumer:
      enabled: true
      group: devGroup

