server:
  port: 8082

spring:
  session:
    store-type: none

  dubbo:
    appname: manager-web
    registry: zookeeper://127.0.0.1:2181
    protocol: dubbo
    group: devGroup
  data:
   solr:
     host: http://112.74.163.29:8983/solr
 ##    zk-host:

application:
  cache:
    confpath: /com/ai/paas/cache/conf
  session:
    confpath: /com/ai/paas/session/conf
  image:
    confpath: /com/ai/paas/gmimage/conf
  file:
    confpath: /com/ai/paas/file/conf
  captcha:
    confpath: /com/ai/paas/qrcode/conf
