server:
  port: 8082

spring:
  session:
    store-type: none

  dubbo:
    appname: manager-web
    registry: zookeeper://127.0.0.1:2181
    protocol: dubbo
    group: devGroup

#  dubbo:
#    application:
#      name: manager-web
#      owner: owner
#      environment: develop
#    protocol:
#      port: 20880
#      threads: 300
#    registry:
#      address: 127.0.0.1:2181
#    monitor:
#      enabled: false
#    provider:
#      enabled: false
#    consumer:
#      enabled: true
#      group: devGroup
