package com.ai.bdex.dataexchange.usercenter.dao.model;

import java.util.Date;

public class AuthRole2Menu extends AuthRole2MenuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_role_2_menu.status
     *
     * @mbg.generated Mon May 22 12:40:05 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_role_2_menu.update_id
     *
     * @mbg.generated Mon May 22 12:40:05 CST 2017
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth_role_2_menu.update_date
     *
     * @mbg.generated Mon May 22 12:40:05 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_role_2_menu.status
     *
     * @return the value of t_auth_role_2_menu.status
     *
     * @mbg.generated Mon May 22 12:40:05 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_role_2_menu.status
     *
     * @param status the value for t_auth_role_2_menu.status
     *
     * @mbg.generated Mon May 22 12:40:05 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_role_2_menu.update_id
     *
     * @return the value of t_auth_role_2_menu.update_id
     *
     * @mbg.generated Mon May 22 12:40:05 CST 2017
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_role_2_menu.update_id
     *
     * @param updateId the value for t_auth_role_2_menu.update_id
     *
     * @mbg.generated Mon May 22 12:40:05 CST 2017
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth_role_2_menu.update_date
     *
     * @return the value of t_auth_role_2_menu.update_date
     *
     * @mbg.generated Mon May 22 12:40:05 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth_role_2_menu.update_date
     *
     * @param updateDate the value for t_auth_role_2_menu.update_date
     *
     * @mbg.generated Mon May 22 12:40:05 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}