spring:
  dubbo:
    application:
      name: woego-dubbo-demo
      owner: owner
      environment: develop
    protocol:
      port: 20881
      threads: 300
    registry:
      address: 127.0.0.1:2181
    provider:
      enabled: true
      group: devGroup
    consumer:
      enabled: false
jdbc:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://112.74.163.29:3306/bdex
  username: bdex
  password: bdex1234

com.ai.auth.login.config: auth
com.ai.paas.zookeeper: 127.0.0.1:2181
com.ai.paas.runmode: D
com.ai.zk.recreate: false

application.sequencefactory.confpath: /com/ai/db/bdex/sequence/conf