spring:
  dubbo:
    application:
      name: woego-dubbo-demo
      owner: owner
      environment: develop
    protocol:
      port: 20882
      threads: 300
    registry:
      address: 127.0.0.1:2181
    provider:
      enabled: true
      group: devGroup
    consumer:
      enabled: false
  data:
   solr:
     host: http://112.74.163.29:8983/solr
jdbc:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://112.74.163.29:3306/bdex?useUnicode=true&characterEncoding=utf8
  username: bdex
  password: bdex1234

application:
  configcenter:
#    login: admin:admin
#    zkaddress: 127.0.0.1:2181
    runmode: D
  sequencefactory:
    confpath: /com/ai/db/sequence/conf
  cache:
    confpath: /com/ai/paas/cache/conf
  session:
    confpath: /com/ai/paas/session/conf