package com.ai.bdex.dataexchange.apigateway.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AipCfcaConfExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    public AipCfcaConfExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPServiceIdIsNull() {
            addCriterion("P_SERVICE_ID is null");
            return (Criteria) this;
        }

        public Criteria andPServiceIdIsNotNull() {
            addCriterion("P_SERVICE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPServiceIdEqualTo(String value) {
            addCriterion("P_SERVICE_ID =", value, "pServiceId");
            return (Criteria) this;
        }

        public Criteria andPServiceIdNotEqualTo(String value) {
            addCriterion("P_SERVICE_ID <>", value, "pServiceId");
            return (Criteria) this;
        }

        public Criteria andPServiceIdGreaterThan(String value) {
            addCriterion("P_SERVICE_ID >", value, "pServiceId");
            return (Criteria) this;
        }

        public Criteria andPServiceIdGreaterThanOrEqualTo(String value) {
            addCriterion("P_SERVICE_ID >=", value, "pServiceId");
            return (Criteria) this;
        }

        public Criteria andPServiceIdLessThan(String value) {
            addCriterion("P_SERVICE_ID <", value, "pServiceId");
            return (Criteria) this;
        }

        public Criteria andPServiceIdLessThanOrEqualTo(String value) {
            addCriterion("P_SERVICE_ID <=", value, "pServiceId");
            return (Criteria) this;
        }

        public Criteria andPServiceIdLike(String value) {
            addCriterion("P_SERVICE_ID like", value, "pServiceId");
            return (Criteria) this;
        }

        public Criteria andPServiceIdNotLike(String value) {
            addCriterion("P_SERVICE_ID not like", value, "pServiceId");
            return (Criteria) this;
        }

        public Criteria andPServiceIdIn(List<String> values) {
            addCriterion("P_SERVICE_ID in", values, "pServiceId");
            return (Criteria) this;
        }

        public Criteria andPServiceIdNotIn(List<String> values) {
            addCriterion("P_SERVICE_ID not in", values, "pServiceId");
            return (Criteria) this;
        }

        public Criteria andPServiceIdBetween(String value1, String value2) {
            addCriterion("P_SERVICE_ID between", value1, value2, "pServiceId");
            return (Criteria) this;
        }

        public Criteria andPServiceIdNotBetween(String value1, String value2) {
            addCriterion("P_SERVICE_ID not between", value1, value2, "pServiceId");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("version like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("version not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeIsNull() {
            addCriterion("transaction_code is null");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeIsNotNull() {
            addCriterion("transaction_code is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeEqualTo(String value) {
            addCriterion("transaction_code =", value, "transactionCode");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeNotEqualTo(String value) {
            addCriterion("transaction_code <>", value, "transactionCode");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeGreaterThan(String value) {
            addCriterion("transaction_code >", value, "transactionCode");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_code >=", value, "transactionCode");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeLessThan(String value) {
            addCriterion("transaction_code <", value, "transactionCode");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeLessThanOrEqualTo(String value) {
            addCriterion("transaction_code <=", value, "transactionCode");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeLike(String value) {
            addCriterion("transaction_code like", value, "transactionCode");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeNotLike(String value) {
            addCriterion("transaction_code not like", value, "transactionCode");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeIn(List<String> values) {
            addCriterion("transaction_code in", values, "transactionCode");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeNotIn(List<String> values) {
            addCriterion("transaction_code not in", values, "transactionCode");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeBetween(String value1, String value2) {
            addCriterion("transaction_code between", value1, value2, "transactionCode");
            return (Criteria) this;
        }

        public Criteria andTransactionCodeNotBetween(String value1, String value2) {
            addCriterion("transaction_code not between", value1, value2, "transactionCode");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixIsNull() {
            addCriterion("url_suffix is null");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixIsNotNull() {
            addCriterion("url_suffix is not null");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixEqualTo(String value) {
            addCriterion("url_suffix =", value, "urlSuffix");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixNotEqualTo(String value) {
            addCriterion("url_suffix <>", value, "urlSuffix");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixGreaterThan(String value) {
            addCriterion("url_suffix >", value, "urlSuffix");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixGreaterThanOrEqualTo(String value) {
            addCriterion("url_suffix >=", value, "urlSuffix");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixLessThan(String value) {
            addCriterion("url_suffix <", value, "urlSuffix");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixLessThanOrEqualTo(String value) {
            addCriterion("url_suffix <=", value, "urlSuffix");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixLike(String value) {
            addCriterion("url_suffix like", value, "urlSuffix");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixNotLike(String value) {
            addCriterion("url_suffix not like", value, "urlSuffix");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixIn(List<String> values) {
            addCriterion("url_suffix in", values, "urlSuffix");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixNotIn(List<String> values) {
            addCriterion("url_suffix not in", values, "urlSuffix");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixBetween(String value1, String value2) {
            addCriterion("url_suffix between", value1, value2, "urlSuffix");
            return (Criteria) this;
        }

        public Criteria andUrlSuffixNotBetween(String value1, String value2) {
            addCriterion("url_suffix not between", value1, value2, "urlSuffix");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagIsNull() {
            addCriterion("encrypt_flag is null");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagIsNotNull() {
            addCriterion("encrypt_flag is not null");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagEqualTo(String value) {
            addCriterion("encrypt_flag =", value, "encryptFlag");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagNotEqualTo(String value) {
            addCriterion("encrypt_flag <>", value, "encryptFlag");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagGreaterThan(String value) {
            addCriterion("encrypt_flag >", value, "encryptFlag");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagGreaterThanOrEqualTo(String value) {
            addCriterion("encrypt_flag >=", value, "encryptFlag");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagLessThan(String value) {
            addCriterion("encrypt_flag <", value, "encryptFlag");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagLessThanOrEqualTo(String value) {
            addCriterion("encrypt_flag <=", value, "encryptFlag");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagLike(String value) {
            addCriterion("encrypt_flag like", value, "encryptFlag");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagNotLike(String value) {
            addCriterion("encrypt_flag not like", value, "encryptFlag");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagIn(List<String> values) {
            addCriterion("encrypt_flag in", values, "encryptFlag");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagNotIn(List<String> values) {
            addCriterion("encrypt_flag not in", values, "encryptFlag");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagBetween(String value1, String value2) {
            addCriterion("encrypt_flag between", value1, value2, "encryptFlag");
            return (Criteria) this;
        }

        public Criteria andEncryptFlagNotBetween(String value1, String value2) {
            addCriterion("encrypt_flag not between", value1, value2, "encryptFlag");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagIsNull() {
            addCriterion("Async_flag is null");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagIsNotNull() {
            addCriterion("Async_flag is not null");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagEqualTo(String value) {
            addCriterion("Async_flag =", value, "asyncFlag");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagNotEqualTo(String value) {
            addCriterion("Async_flag <>", value, "asyncFlag");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagGreaterThan(String value) {
            addCriterion("Async_flag >", value, "asyncFlag");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagGreaterThanOrEqualTo(String value) {
            addCriterion("Async_flag >=", value, "asyncFlag");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagLessThan(String value) {
            addCriterion("Async_flag <", value, "asyncFlag");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagLessThanOrEqualTo(String value) {
            addCriterion("Async_flag <=", value, "asyncFlag");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagLike(String value) {
            addCriterion("Async_flag like", value, "asyncFlag");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagNotLike(String value) {
            addCriterion("Async_flag not like", value, "asyncFlag");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagIn(List<String> values) {
            addCriterion("Async_flag in", values, "asyncFlag");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagNotIn(List<String> values) {
            addCriterion("Async_flag not in", values, "asyncFlag");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagBetween(String value1, String value2) {
            addCriterion("Async_flag between", value1, value2, "asyncFlag");
            return (Criteria) this;
        }

        public Criteria andAsyncFlagNotBetween(String value1, String value2) {
            addCriterion("Async_flag not between", value1, value2, "asyncFlag");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated do_not_delete_during_merge Mon May 22 19:53:00 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_aip_cfca_conf
     *
     * @mbg.generated Mon May 22 19:53:00 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}