package com.ai.bdex.dataexchange.apigateway.dao.model;

import java.util.Date;

public class AipServiceSpring extends AipServiceSpringKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aip_service_spring.bean_name
     *
     * @mbg.generated Sat Jun 03 14:54:19 CST 2017
     */
    private String beanName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aip_service_spring.create_time
     *
     * @mbg.generated Sat Jun 03 14:54:19 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aip_service_spring.pservice_flag
     *
     * @mbg.generated Sat Jun 03 14:54:19 CST 2017
     */
    private String pserviceFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_aip_service_spring.store_flag
     *
     * @mbg.generated Sat Jun 03 14:54:19 CST 2017
     */
    private String storeFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aip_service_spring.bean_name
     *
     * @return the value of t_aip_service_spring.bean_name
     *
     * @mbg.generated Sat Jun 03 14:54:19 CST 2017
     */
    public String getBeanName() {
        return beanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aip_service_spring.bean_name
     *
     * @param beanName the value for t_aip_service_spring.bean_name
     *
     * @mbg.generated Sat Jun 03 14:54:19 CST 2017
     */
    public void setBeanName(String beanName) {
        this.beanName = beanName == null ? null : beanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aip_service_spring.create_time
     *
     * @return the value of t_aip_service_spring.create_time
     *
     * @mbg.generated Sat Jun 03 14:54:19 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aip_service_spring.create_time
     *
     * @param createTime the value for t_aip_service_spring.create_time
     *
     * @mbg.generated Sat Jun 03 14:54:19 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aip_service_spring.pservice_flag
     *
     * @return the value of t_aip_service_spring.pservice_flag
     *
     * @mbg.generated Sat Jun 03 14:54:19 CST 2017
     */
    public String getPserviceFlag() {
        return pserviceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aip_service_spring.pservice_flag
     *
     * @param pserviceFlag the value for t_aip_service_spring.pservice_flag
     *
     * @mbg.generated Sat Jun 03 14:54:19 CST 2017
     */
    public void setPserviceFlag(String pserviceFlag) {
        this.pserviceFlag = pserviceFlag == null ? null : pserviceFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_aip_service_spring.store_flag
     *
     * @return the value of t_aip_service_spring.store_flag
     *
     * @mbg.generated Sat Jun 03 14:54:19 CST 2017
     */
    public String getStoreFlag() {
        return storeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_aip_service_spring.store_flag
     *
     * @param storeFlag the value for t_aip_service_spring.store_flag
     *
     * @mbg.generated Sat Jun 03 14:54:19 CST 2017
     */
    public void setStoreFlag(String storeFlag) {
        this.storeFlag = storeFlag == null ? null : storeFlag.trim();
    }
}