package com.ai.bdex.dataexchange.apigateway.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class DataAccountHisExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    public DataAccountHisExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andHisIdIsNull() {
            addCriterion("his_id is null");
            return (Criteria) this;
        }

        public Criteria andHisIdIsNotNull() {
            addCriterion("his_id is not null");
            return (Criteria) this;
        }

        public Criteria andHisIdEqualTo(Long value) {
            addCriterion("his_id =", value, "hisId");
            return (Criteria) this;
        }

        public Criteria andHisIdNotEqualTo(Long value) {
            addCriterion("his_id <>", value, "hisId");
            return (Criteria) this;
        }

        public Criteria andHisIdGreaterThan(Long value) {
            addCriterion("his_id >", value, "hisId");
            return (Criteria) this;
        }

        public Criteria andHisIdGreaterThanOrEqualTo(Long value) {
            addCriterion("his_id >=", value, "hisId");
            return (Criteria) this;
        }

        public Criteria andHisIdLessThan(Long value) {
            addCriterion("his_id <", value, "hisId");
            return (Criteria) this;
        }

        public Criteria andHisIdLessThanOrEqualTo(Long value) {
            addCriterion("his_id <=", value, "hisId");
            return (Criteria) this;
        }

        public Criteria andHisIdIn(List<Long> values) {
            addCriterion("his_id in", values, "hisId");
            return (Criteria) this;
        }

        public Criteria andHisIdNotIn(List<Long> values) {
            addCriterion("his_id not in", values, "hisId");
            return (Criteria) this;
        }

        public Criteria andHisIdBetween(Long value1, Long value2) {
            addCriterion("his_id between", value1, value2, "hisId");
            return (Criteria) this;
        }

        public Criteria andHisIdNotBetween(Long value1, Long value2) {
            addCriterion("his_id not between", value1, value2, "hisId");
            return (Criteria) this;
        }

        public Criteria andDataAcctIdIsNull() {
            addCriterion("data_acct_id is null");
            return (Criteria) this;
        }

        public Criteria andDataAcctIdIsNotNull() {
            addCriterion("data_acct_id is not null");
            return (Criteria) this;
        }

        public Criteria andDataAcctIdEqualTo(Long value) {
            addCriterion("data_acct_id =", value, "dataAcctId");
            return (Criteria) this;
        }

        public Criteria andDataAcctIdNotEqualTo(Long value) {
            addCriterion("data_acct_id <>", value, "dataAcctId");
            return (Criteria) this;
        }

        public Criteria andDataAcctIdGreaterThan(Long value) {
            addCriterion("data_acct_id >", value, "dataAcctId");
            return (Criteria) this;
        }

        public Criteria andDataAcctIdGreaterThanOrEqualTo(Long value) {
            addCriterion("data_acct_id >=", value, "dataAcctId");
            return (Criteria) this;
        }

        public Criteria andDataAcctIdLessThan(Long value) {
            addCriterion("data_acct_id <", value, "dataAcctId");
            return (Criteria) this;
        }

        public Criteria andDataAcctIdLessThanOrEqualTo(Long value) {
            addCriterion("data_acct_id <=", value, "dataAcctId");
            return (Criteria) this;
        }

        public Criteria andDataAcctIdIn(List<Long> values) {
            addCriterion("data_acct_id in", values, "dataAcctId");
            return (Criteria) this;
        }

        public Criteria andDataAcctIdNotIn(List<Long> values) {
            addCriterion("data_acct_id not in", values, "dataAcctId");
            return (Criteria) this;
        }

        public Criteria andDataAcctIdBetween(Long value1, Long value2) {
            addCriterion("data_acct_id between", value1, value2, "dataAcctId");
            return (Criteria) this;
        }

        public Criteria andDataAcctIdNotBetween(Long value1, Long value2) {
            addCriterion("data_acct_id not between", value1, value2, "dataAcctId");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeIsNull() {
            addCriterion("data_acct_type is null");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeIsNotNull() {
            addCriterion("data_acct_type is not null");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeEqualTo(String value) {
            addCriterion("data_acct_type =", value, "dataAcctType");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeNotEqualTo(String value) {
            addCriterion("data_acct_type <>", value, "dataAcctType");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeGreaterThan(String value) {
            addCriterion("data_acct_type >", value, "dataAcctType");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeGreaterThanOrEqualTo(String value) {
            addCriterion("data_acct_type >=", value, "dataAcctType");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeLessThan(String value) {
            addCriterion("data_acct_type <", value, "dataAcctType");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeLessThanOrEqualTo(String value) {
            addCriterion("data_acct_type <=", value, "dataAcctType");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeLike(String value) {
            addCriterion("data_acct_type like", value, "dataAcctType");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeNotLike(String value) {
            addCriterion("data_acct_type not like", value, "dataAcctType");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeIn(List<String> values) {
            addCriterion("data_acct_type in", values, "dataAcctType");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeNotIn(List<String> values) {
            addCriterion("data_acct_type not in", values, "dataAcctType");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeBetween(String value1, String value2) {
            addCriterion("data_acct_type between", value1, value2, "dataAcctType");
            return (Criteria) this;
        }

        public Criteria andDataAcctTypeNotBetween(String value1, String value2) {
            addCriterion("data_acct_type not between", value1, value2, "dataAcctType");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeIsNull() {
            addCriterion("period_type is null");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeIsNotNull() {
            addCriterion("period_type is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeEqualTo(String value) {
            addCriterion("period_type =", value, "periodType");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeNotEqualTo(String value) {
            addCriterion("period_type <>", value, "periodType");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeGreaterThan(String value) {
            addCriterion("period_type >", value, "periodType");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeGreaterThanOrEqualTo(String value) {
            addCriterion("period_type >=", value, "periodType");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeLessThan(String value) {
            addCriterion("period_type <", value, "periodType");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeLessThanOrEqualTo(String value) {
            addCriterion("period_type <=", value, "periodType");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeLike(String value) {
            addCriterion("period_type like", value, "periodType");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeNotLike(String value) {
            addCriterion("period_type not like", value, "periodType");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeIn(List<String> values) {
            addCriterion("period_type in", values, "periodType");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeNotIn(List<String> values) {
            addCriterion("period_type not in", values, "periodType");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeBetween(String value1, String value2) {
            addCriterion("period_type between", value1, value2, "periodType");
            return (Criteria) this;
        }

        public Criteria andPeriodTypeNotBetween(String value1, String value2) {
            addCriterion("period_type not between", value1, value2, "periodType");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNull() {
            addCriterion("service_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNotNull() {
            addCriterion("service_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceIdEqualTo(String value) {
            addCriterion("service_id =", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotEqualTo(String value) {
            addCriterion("service_id <>", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThan(String value) {
            addCriterion("service_id >", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThanOrEqualTo(String value) {
            addCriterion("service_id >=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThan(String value) {
            addCriterion("service_id <", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThanOrEqualTo(String value) {
            addCriterion("service_id <=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLike(String value) {
            addCriterion("service_id like", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotLike(String value) {
            addCriterion("service_id not like", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdIn(List<String> values) {
            addCriterion("service_id in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotIn(List<String> values) {
            addCriterion("service_id not in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdBetween(String value1, String value2) {
            addCriterion("service_id between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotBetween(String value1, String value2) {
            addCriterion("service_id not between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andTotalNumIsNull() {
            addCriterion("total_num is null");
            return (Criteria) this;
        }

        public Criteria andTotalNumIsNotNull() {
            addCriterion("total_num is not null");
            return (Criteria) this;
        }

        public Criteria andTotalNumEqualTo(Integer value) {
            addCriterion("total_num =", value, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumNotEqualTo(Integer value) {
            addCriterion("total_num <>", value, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumGreaterThan(Integer value) {
            addCriterion("total_num >", value, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_num >=", value, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumLessThan(Integer value) {
            addCriterion("total_num <", value, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumLessThanOrEqualTo(Integer value) {
            addCriterion("total_num <=", value, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumIn(List<Integer> values) {
            addCriterion("total_num in", values, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumNotIn(List<Integer> values) {
            addCriterion("total_num not in", values, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumBetween(Integer value1, Integer value2) {
            addCriterion("total_num between", value1, value2, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumNotBetween(Integer value1, Integer value2) {
            addCriterion("total_num not between", value1, value2, "totalNum");
            return (Criteria) this;
        }

        public Criteria andLeftNumIsNull() {
            addCriterion("left_num is null");
            return (Criteria) this;
        }

        public Criteria andLeftNumIsNotNull() {
            addCriterion("left_num is not null");
            return (Criteria) this;
        }

        public Criteria andLeftNumEqualTo(Integer value) {
            addCriterion("left_num =", value, "leftNum");
            return (Criteria) this;
        }

        public Criteria andLeftNumNotEqualTo(Integer value) {
            addCriterion("left_num <>", value, "leftNum");
            return (Criteria) this;
        }

        public Criteria andLeftNumGreaterThan(Integer value) {
            addCriterion("left_num >", value, "leftNum");
            return (Criteria) this;
        }

        public Criteria andLeftNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("left_num >=", value, "leftNum");
            return (Criteria) this;
        }

        public Criteria andLeftNumLessThan(Integer value) {
            addCriterion("left_num <", value, "leftNum");
            return (Criteria) this;
        }

        public Criteria andLeftNumLessThanOrEqualTo(Integer value) {
            addCriterion("left_num <=", value, "leftNum");
            return (Criteria) this;
        }

        public Criteria andLeftNumIn(List<Integer> values) {
            addCriterion("left_num in", values, "leftNum");
            return (Criteria) this;
        }

        public Criteria andLeftNumNotIn(List<Integer> values) {
            addCriterion("left_num not in", values, "leftNum");
            return (Criteria) this;
        }

        public Criteria andLeftNumBetween(Integer value1, Integer value2) {
            addCriterion("left_num between", value1, value2, "leftNum");
            return (Criteria) this;
        }

        public Criteria andLeftNumNotBetween(Integer value1, Integer value2) {
            addCriterion("left_num not between", value1, value2, "leftNum");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeNumIsNull() {
            addCriterion("total_consume_num is null");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeNumIsNotNull() {
            addCriterion("total_consume_num is not null");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeNumEqualTo(Integer value) {
            addCriterion("total_consume_num =", value, "totalConsumeNum");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeNumNotEqualTo(Integer value) {
            addCriterion("total_consume_num <>", value, "totalConsumeNum");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeNumGreaterThan(Integer value) {
            addCriterion("total_consume_num >", value, "totalConsumeNum");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_consume_num >=", value, "totalConsumeNum");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeNumLessThan(Integer value) {
            addCriterion("total_consume_num <", value, "totalConsumeNum");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeNumLessThanOrEqualTo(Integer value) {
            addCriterion("total_consume_num <=", value, "totalConsumeNum");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeNumIn(List<Integer> values) {
            addCriterion("total_consume_num in", values, "totalConsumeNum");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeNumNotIn(List<Integer> values) {
            addCriterion("total_consume_num not in", values, "totalConsumeNum");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeNumBetween(Integer value1, Integer value2) {
            addCriterion("total_consume_num between", value1, value2, "totalConsumeNum");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeNumNotBetween(Integer value1, Integer value2) {
            addCriterion("total_consume_num not between", value1, value2, "totalConsumeNum");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyIsNull() {
            addCriterion("total_money is null");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyIsNotNull() {
            addCriterion("total_money is not null");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyEqualTo(Integer value) {
            addCriterion("total_money =", value, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyNotEqualTo(Integer value) {
            addCriterion("total_money <>", value, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyGreaterThan(Integer value) {
            addCriterion("total_money >", value, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_money >=", value, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyLessThan(Integer value) {
            addCriterion("total_money <", value, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyLessThanOrEqualTo(Integer value) {
            addCriterion("total_money <=", value, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyIn(List<Integer> values) {
            addCriterion("total_money in", values, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyNotIn(List<Integer> values) {
            addCriterion("total_money not in", values, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyBetween(Integer value1, Integer value2) {
            addCriterion("total_money between", value1, value2, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andTotalMoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("total_money not between", value1, value2, "totalMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyIsNull() {
            addCriterion("left_money is null");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyIsNotNull() {
            addCriterion("left_money is not null");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyEqualTo(Integer value) {
            addCriterion("left_money =", value, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyNotEqualTo(Integer value) {
            addCriterion("left_money <>", value, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyGreaterThan(Integer value) {
            addCriterion("left_money >", value, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("left_money >=", value, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyLessThan(Integer value) {
            addCriterion("left_money <", value, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyLessThanOrEqualTo(Integer value) {
            addCriterion("left_money <=", value, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyIn(List<Integer> values) {
            addCriterion("left_money in", values, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyNotIn(List<Integer> values) {
            addCriterion("left_money not in", values, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyBetween(Integer value1, Integer value2) {
            addCriterion("left_money between", value1, value2, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andLeftMoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("left_money not between", value1, value2, "leftMoney");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeMoneyIsNull() {
            addCriterion("total_consume_money is null");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeMoneyIsNotNull() {
            addCriterion("total_consume_money is not null");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeMoneyEqualTo(Integer value) {
            addCriterion("total_consume_money =", value, "totalConsumeMoney");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeMoneyNotEqualTo(Integer value) {
            addCriterion("total_consume_money <>", value, "totalConsumeMoney");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeMoneyGreaterThan(Integer value) {
            addCriterion("total_consume_money >", value, "totalConsumeMoney");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeMoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_consume_money >=", value, "totalConsumeMoney");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeMoneyLessThan(Integer value) {
            addCriterion("total_consume_money <", value, "totalConsumeMoney");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeMoneyLessThanOrEqualTo(Integer value) {
            addCriterion("total_consume_money <=", value, "totalConsumeMoney");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeMoneyIn(List<Integer> values) {
            addCriterion("total_consume_money in", values, "totalConsumeMoney");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeMoneyNotIn(List<Integer> values) {
            addCriterion("total_consume_money not in", values, "totalConsumeMoney");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeMoneyBetween(Integer value1, Integer value2) {
            addCriterion("total_consume_money between", value1, value2, "totalConsumeMoney");
            return (Criteria) this;
        }

        public Criteria andTotalConsumeMoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("total_consume_money not between", value1, value2, "totalConsumeMoney");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterionForJDBCDate("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterionForJDBCDate("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusIsNull() {
            addCriterion("data_acct_status is null");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusIsNotNull() {
            addCriterion("data_acct_status is not null");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusEqualTo(String value) {
            addCriterion("data_acct_status =", value, "dataAcctStatus");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusNotEqualTo(String value) {
            addCriterion("data_acct_status <>", value, "dataAcctStatus");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusGreaterThan(String value) {
            addCriterion("data_acct_status >", value, "dataAcctStatus");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusGreaterThanOrEqualTo(String value) {
            addCriterion("data_acct_status >=", value, "dataAcctStatus");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusLessThan(String value) {
            addCriterion("data_acct_status <", value, "dataAcctStatus");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusLessThanOrEqualTo(String value) {
            addCriterion("data_acct_status <=", value, "dataAcctStatus");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusLike(String value) {
            addCriterion("data_acct_status like", value, "dataAcctStatus");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusNotLike(String value) {
            addCriterion("data_acct_status not like", value, "dataAcctStatus");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusIn(List<String> values) {
            addCriterion("data_acct_status in", values, "dataAcctStatus");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusNotIn(List<String> values) {
            addCriterion("data_acct_status not in", values, "dataAcctStatus");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusBetween(String value1, String value2) {
            addCriterion("data_acct_status between", value1, value2, "dataAcctStatus");
            return (Criteria) this;
        }

        public Criteria andDataAcctStatusNotBetween(String value1, String value2) {
            addCriterion("data_acct_status not between", value1, value2, "dataAcctStatus");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateStaffIsNull() {
            addCriterion("create_staff is null");
            return (Criteria) this;
        }

        public Criteria andCreateStaffIsNotNull() {
            addCriterion("create_staff is not null");
            return (Criteria) this;
        }

        public Criteria andCreateStaffEqualTo(String value) {
            addCriterion("create_staff =", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffNotEqualTo(String value) {
            addCriterion("create_staff <>", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffGreaterThan(String value) {
            addCriterion("create_staff >", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffGreaterThanOrEqualTo(String value) {
            addCriterion("create_staff >=", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffLessThan(String value) {
            addCriterion("create_staff <", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffLessThanOrEqualTo(String value) {
            addCriterion("create_staff <=", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffLike(String value) {
            addCriterion("create_staff like", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffNotLike(String value) {
            addCriterion("create_staff not like", value, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffIn(List<String> values) {
            addCriterion("create_staff in", values, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffNotIn(List<String> values) {
            addCriterion("create_staff not in", values, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffBetween(String value1, String value2) {
            addCriterion("create_staff between", value1, value2, "createStaff");
            return (Criteria) this;
        }

        public Criteria andCreateStaffNotBetween(String value1, String value2) {
            addCriterion("create_staff not between", value1, value2, "createStaff");
            return (Criteria) this;
        }

        public Criteria andPackageTypeIsNull() {
            addCriterion("package_type is null");
            return (Criteria) this;
        }

        public Criteria andPackageTypeIsNotNull() {
            addCriterion("package_type is not null");
            return (Criteria) this;
        }

        public Criteria andPackageTypeEqualTo(String value) {
            addCriterion("package_type =", value, "packageType");
            return (Criteria) this;
        }

        public Criteria andPackageTypeNotEqualTo(String value) {
            addCriterion("package_type <>", value, "packageType");
            return (Criteria) this;
        }

        public Criteria andPackageTypeGreaterThan(String value) {
            addCriterion("package_type >", value, "packageType");
            return (Criteria) this;
        }

        public Criteria andPackageTypeGreaterThanOrEqualTo(String value) {
            addCriterion("package_type >=", value, "packageType");
            return (Criteria) this;
        }

        public Criteria andPackageTypeLessThan(String value) {
            addCriterion("package_type <", value, "packageType");
            return (Criteria) this;
        }

        public Criteria andPackageTypeLessThanOrEqualTo(String value) {
            addCriterion("package_type <=", value, "packageType");
            return (Criteria) this;
        }

        public Criteria andPackageTypeLike(String value) {
            addCriterion("package_type like", value, "packageType");
            return (Criteria) this;
        }

        public Criteria andPackageTypeNotLike(String value) {
            addCriterion("package_type not like", value, "packageType");
            return (Criteria) this;
        }

        public Criteria andPackageTypeIn(List<String> values) {
            addCriterion("package_type in", values, "packageType");
            return (Criteria) this;
        }

        public Criteria andPackageTypeNotIn(List<String> values) {
            addCriterion("package_type not in", values, "packageType");
            return (Criteria) this;
        }

        public Criteria andPackageTypeBetween(String value1, String value2) {
            addCriterion("package_type between", value1, value2, "packageType");
            return (Criteria) this;
        }

        public Criteria andPackageTypeNotBetween(String value1, String value2) {
            addCriterion("package_type not between", value1, value2, "packageType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_data_account_his
     *
     * @mbg.generated do_not_delete_during_merge Mon May 15 22:20:25 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_data_account_his
     *
     * @mbg.generated Mon May 15 22:20:25 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}