server:
  port: 8081

spring:
  session:
    store-type: none
  dubbo:
    appname: mall-web
    registry: zookeeper://127.0.0.1:2181
    protocol: dubbo
    group: devGroup
  thymeleaf:
    enabled: true
    cache: false
    suffix: .html
    encoding: UTF-8
  data:
   solr:
     host: http://112.74.163.29:8983/solr
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**


## woego-frame框架包配置
application:
  cache:
    confpath: /com/ai/paas/cache/conf
  session:
    confpath: /com/ai/paas/session/conf
    systemcode: "01"
  image:
    confpath: /com/ai/paas/gmimage/conf
  file:
    confpath: /com/ai/paas/file/conf
  captcha:
    confpath: /com/ai/paas/qrcode/conf
    qrservleturlpattern: /qrcode/*
    captchaservleturlpattern: /captcha/CapthcaImage
  system:
    confpath: /com/ai/paas/system/conf
  configcenter:
    runmode: D
    zkaddress: 127.0.0.1:2181
    login: admin:admin
  filter:
    enabled: true
    ignoreSuffix: ".ico,.swf,.flv,.png,.jpg,.jpeg,.gif,.css,.js,.html,.htm,.eot,.svg,.ttf,.woff,.mp4,.woff2,.map"
    unloginflag: true
  alipay:
    aliGateway: "https://openapi.alipay.com/gateway.do"
    appId: "2017050507124732"
    privateKey: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDSU+uJUvFPCC57kPxVIJM/22iJLAsoH6rNx4wVuXGpoyLzSKKZhgdMiW+bUB5Qy7OCfhhz4mcYWxU1wRzPTK3ODstDV6na9F8JmOQbFLfte6Y3f4gvXCWcEGdSfT5O+94TlzlnsWwywvKNDeoczjksrUMb/CcgmsADKR+DOlTUFpmMqmN4QelxFapDNmuZHFNWfxBsOmHJb06xKKdbif7NT+DuFFF9Bs84uNziATdcguO0cf9KuM3a1nbmzMn3dcD6qiUiR/OB134DsAF+gVPRoqTB0WK4AKktThd5suzPFTf8skWuRpVMbDiyEsIrRAPy8NJXdsNfqDyPq/8U5I3BAgMBAAECggEBAKMbL1I8PyQh3SI4Kma9r1NbDDMsM662+BdCw1DpkcqS13zA/E+AT9K71hAkzo2rmpb8wGvFzFtn7wfTrUrZVQOyF1Eu/2rsDXN83JBfvc7uD9WEEhFgLU5crjObKqHH0s1wfbT7M0QeSEi43K/gARizeJKQNaukNnl8/5Idv0EEqSSVhGxe4ETeY5k3Jpz/0G5ID5RRUwRZhq0kAUhlY+GaH6oaXUxJgMS/J2dyYlrSMU57lhW5ud6lfbpo/5RbsduqXjJL23t0JOfzdFIdt1XX47PYypJQ8JqznXTyrWh5MiGYUzbie2rMYKWGTkpHfmUC5Wh+ptN5gkiBpv05ZkECgYEA9hJ+SMKW/sBai42sk47/Dr2ctK9jeDGjV0aqFN+xhr3iB9/GOW2j7NQPBzVEDq7c3vkbVzGngSjjd5miWEu22t8OiaFm2EAuBlcKW286bNUxYIlqLkqwIKv7fHf4Fbhy+8xd8wl1dDeJVDbo+QkvEYGEvNwdV69NbGvQYCnNG4kCgYEA2tA/bn37Khk41+ZUNwIO0HtS992JJfBdvqebIqnUsJTcj893m49jySQaenSAOJ/sun8uW2gbAhLkJq1GXBCkavRIOqwP4ICXm/N3e30FFJLwgXKNyWslZBVyf+Jc+3h2Bs0+FHrjw9LQ2jngtBcbapM5gml2WNgw/xDFzsQpunkCgYBXU7TRaY1gly8K+5pVO5g0yQHF9cBdNXB8Vq2hfslnwhdnJ/kXBFv6fj9fFX4zn8busoULaqnBYptnJHTC1QvtnN9x5H+1GwG6akVYsZ6QZRCC7AFssEDVN3OmdoTqYG0eAycMSz0No2/vHRWM27+CfO54f71CEwptAc4PcoZB0QKBgGTk/0qohoar6J0M1KokpcYWB3TJTvMSeXdu+0apfqwJiAY7yNAO9xkJL7hlPbZeb56zBCIbx9BV+6Ol5DqRZe73QtLjAdMoGEBNrDths1UASCu4MY69fBlBFnHHY86Ehg+u1cBFxf5GmAz4ARepS/gBeNQcYvimfzktd7hWlVMpAoGBANzngNoE1tA8CBx75I7CSFdsExXTUF9SzU6S8Af2U1+uQpGOu/22AueMFm0E2QzerZcBdIgx1YXoZm1HgNnvq+SRSobancTKnJ+6JjYNOlPPgoBszP1dftRCDLVz5hIB2nnPDAIXktd17SRymD9MLX/kTc2cxyWeWI9scgbcoxIQ"
    format: "json"
    charset: "UTF-8"
    alipayPulicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnijJMKASQCQLjRtotiXeIfl1dzVANJfi581mvgKhOzmxuB4G0hTd+EbxQG3/kV36PnYAwrT1BPobwW3L6aoSKOhkQfmPBbPO1Pd6F1llCxhBUZV2erAwfEAOdMp/VZhf+ck6YWrO4364MK18m6UeAVTebv2mJe3c5Q4wVl2hHtiSlnkljj4KrW3BdUKNJ91uy0ak0dwtEl7Owt9lTNE2Syo1rjSpsc3YidFQm0WVqIHgUd8PfiIUwI+/7vQfxluAt6gOSpf47n5U4SPHKhzB8WOwo3tS/Xpb2EXrAQZ2/NOfyIp0aye6IEK42RCv5+uRQSYinZC3MXcWHspKjWz0QwIDAQAB"
    signType: "RSA2"
    returnUrl: "http://112.74.163.29:8083/manager-web/orderManage/myOrder"
    notifyUrl: "http://112.74.163.29:8082/mall-web/bdxalipay/alipayNotify"