server:
  port: 8081

spring:
  session:
    store-type: none
  dubbo:
    appname: mall-web
    registry: zookeeper://127.0.0.1:2181
    protocol: dubbo
    group: devGroup
  thymeleaf:
    enabled: true
    cache: false
    suffix: .html
    encoding: UTF-8

## woego-frame框架包配置
application:
  cache:
    confpath: /com/ai/paas/cache/conf
  session:
    confpath: /com/ai/paas/session/conf
  image:
    confpath: /com/ai/paas/image/conf
  file:
    confpath: /com/ai/paas/file/conf
  configcenter:
    runmode: D
    zkaddress: 127.0.0.1:2181
    login: admin:admin