server:
  port: 8081

spring:
  session:
    store-type: none
  dubbo:
    appname: mall-web
    registry: zookeeper://127.0.0.1:2181
    protocol: dubbo
    group: devGroup
  thymeleaf:
    enabled: true
    cache: false
    suffix: .html
    encoding: UTF-8
  data:
   solr:
     host: http://112.74.163.29:8983/solr
 ##    zk-host:

## woego-frame框架包配置
application:
  cache:
    confpath: /com/ai/paas/cache/conf
  session:
    confpath: /com/ai/paas/session/conf
  image:
    confpath: /com/ai/paas/gmimage/conf
  file:
    confpath: /com/ai/paas/file/conf
  captcha:
    confpath: /com/ai/paas/qrcode/conf
    qrservleturlpattern: /qrcode/*
    captchaservleturlpattern: /captcha/CapthcaImage
  system:
    confpath: /com/ai/paas/system/conf
  configcenter:
    runmode: D
    zkaddress: 127.0.0.1:2181
    login: admin:admin