spring:
  dubbo:
    application:
      name: woego-dubbo-demo
      owner: owner
      environment: develop
    protocol:
      port: 20880
      threads: 300
    registry:
      address: 127.0.0.1:2181
    provider:
      enabled: true
      group: devGroup
    consumer:
      enabled: false
      
jdbc:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://localhost:3305/qcs
  username: root
  password: 1234