spring:
  dubbo:
    application:
      name: woego-dubbo-demo
      owner: owner
      environment: develop
    protocol:
      port: 20880
      threads: 300
    registry:
      address: 132.37.2.41:29181
    provider:
      enabled: true
      group: devGroup
    consumer:
      enabled: false
      
jdbc:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://132.37.2.102:39306/mp_woego
  username: wegmpusr
  password: wegmpusr@123