spring:
  jps:
    showsql: true
  dubbo:
    application:
      name: apigateway-dubbo-demo
      owner: owner
      environment: develop
    protocol:
      port: 20885
      threads: 300
    registry:
      address: 127.0.0.1:2181
    provider:
      enabled: true
      group: devGroup
    consumer:
      enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.74.163.29:3306/bdex?useUnicode=true&characterEncoding=utf8
    username: bdex
    password: bdex1234

logging:
  level:
    root: debug

mybatis:
  mapper-locations: classpath:/sqlmapper/**/*.xml
  type-aliases-package: com.ai.bdex.dataexchange.*.dao.model
pagehelper:
  helperDialect: mysql

application:
  configcenter:
#    login: admin:admin
#    zkaddress: 127.0.0.1:2181
    runmode: D
  sequencefactory:
    confpath: /com/ai/db/sequence/conf
  cache:
    confpath: /com/ai/paas/cache/conf
  session:
    confpath: /com/ai/paas/session/conf
  image:
    confpath: /com/ai/paas/gmimage/conf
  file:
    confpath: /com/ai/paas/file/conf