package com.ai.bdex.dataexchange.usercenter.dao.model.custom;

public class BaseParamDynamic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_dynamic.PARAM_LINK_KEY
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    private String paramLinkKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_dynamic.PARAM_NAME
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    private String paramName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_dynamic.SQL_LOAD
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    private String sqlLoad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_dynamic.DB_NAME
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    private String dbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_dynamic.TABLE_NAME
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_dynamic.LOAD_TYPE
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    private String loadType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_dynamic.STATUS
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_param_dynamic.SP_DESC
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    private String spDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_dynamic.PARAM_LINK_KEY
     *
     * @return the value of t_base_param_dynamic.PARAM_LINK_KEY
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public String getParamLinkKey() {
        return paramLinkKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_dynamic.PARAM_LINK_KEY
     *
     * @param paramLinkKey the value for t_base_param_dynamic.PARAM_LINK_KEY
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public void setParamLinkKey(String paramLinkKey) {
        this.paramLinkKey = paramLinkKey == null ? null : paramLinkKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_dynamic.PARAM_NAME
     *
     * @return the value of t_base_param_dynamic.PARAM_NAME
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_dynamic.PARAM_NAME
     *
     * @param paramName the value for t_base_param_dynamic.PARAM_NAME
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_dynamic.SQL_LOAD
     *
     * @return the value of t_base_param_dynamic.SQL_LOAD
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public String getSqlLoad() {
        return sqlLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_dynamic.SQL_LOAD
     *
     * @param sqlLoad the value for t_base_param_dynamic.SQL_LOAD
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public void setSqlLoad(String sqlLoad) {
        this.sqlLoad = sqlLoad == null ? null : sqlLoad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_dynamic.DB_NAME
     *
     * @return the value of t_base_param_dynamic.DB_NAME
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_dynamic.DB_NAME
     *
     * @param dbName the value for t_base_param_dynamic.DB_NAME
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public void setDbName(String dbName) {
        this.dbName = dbName == null ? null : dbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_dynamic.TABLE_NAME
     *
     * @return the value of t_base_param_dynamic.TABLE_NAME
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_dynamic.TABLE_NAME
     *
     * @param tableName the value for t_base_param_dynamic.TABLE_NAME
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_dynamic.LOAD_TYPE
     *
     * @return the value of t_base_param_dynamic.LOAD_TYPE
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public String getLoadType() {
        return loadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_dynamic.LOAD_TYPE
     *
     * @param loadType the value for t_base_param_dynamic.LOAD_TYPE
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public void setLoadType(String loadType) {
        this.loadType = loadType == null ? null : loadType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_dynamic.STATUS
     *
     * @return the value of t_base_param_dynamic.STATUS
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_dynamic.STATUS
     *
     * @param status the value for t_base_param_dynamic.STATUS
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_param_dynamic.SP_DESC
     *
     * @return the value of t_base_param_dynamic.SP_DESC
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public String getSpDesc() {
        return spDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_param_dynamic.SP_DESC
     *
     * @param spDesc the value for t_base_param_dynamic.SP_DESC
     *
     * @mbg.generated Tue Apr 18 16:26:14 CST 2017
     */
    public void setSpDesc(String spDesc) {
        this.spDesc = spDesc == null ? null : spDesc.trim();
    }
}